# Generated by Django 2.2.5 on 2020-02-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='globalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('diagnosed', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('death', models.IntegerField()),
                ('new_death', models.IntegerField()),
                ('discharged', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
