# Generated by Django 2.2.5 on 2020-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_globallastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOHheadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_link', models.URLField()),
            ],
        ),
    ]
