# Generated by Django 2.2.5 on 2020-03-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_mohheadlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='mohheadlines',
            name='news_date',
            field=models.DateField(null=True),
        ),
    ]
