# Generated by Django 2.2.5 on 2020-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0004_mohheadlines_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohheadlines',
            name='news_date',
            field=models.DateField(blank=True),
        ),
    ]
