# Generated by Django 2.2.5 on 2020-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0007_auto_20200304_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstatus',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
