# Generated by Django 2.2.5 on 2020-03-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0009_auto_20200308_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('POLYCLINIC', 'Polyclinic')], default='HOSPITAL', max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('geocode_result', models.CharField(max_length=5000)),
            ],
        ),
    ]
