# Generated by Django 2.2.5 on 2020-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0011_diagnosisresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('telegram_user', models.CharField(max_length=100)),
                ('session_ID', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('question', models.CharField(max_length=10000)),
                ('answer', models.CharField(max_length=10000)),
            ],
        ),
    ]
