# Generated by Django 2.2.5 on 2020-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0012_feedbacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='userList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('telegram_user', models.CharField(max_length=100)),
                ('chat_ID', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
