# Generated by Django 2.2.5 on 2020-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0013_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklist',
            name='chat_ID',
            field=models.CharField(default='NONE', max_length=100, unique=True),
        ),
    ]
