# Generated by Django 2.2.5 on 2020-04-20 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0015_auto_20200419_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklist',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 10, 30, 42, 647965)),
        ),
    ]
