# Generated by Django 2.2.5 on 2020-04-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0018_auto_20200420_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graphPlot',
        ),
    ]
