# Generated by Django 2.2.5 on 2020-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0020_graphplot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacklist',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='telegram_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
