# Generated by Django 2.2.5 on 2020-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0022_auto_20200421_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklist',
            name='triggered_intent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
