# Generated by Django 2.2.5 on 2020-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0023_feedbacklist_triggered_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='subscribe',
            field=models.IntegerField(default=1),
        ),
    ]
