# Generated by Django 2.2.5 on 2020-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0024_userlist_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
