# Generated by Django 2.2.10 on 2020-04-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0025_auto_20200421_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresponses',
            name='query_ID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdiagnosis',
            name='diagnosis_result',
            field=models.CharField(max_length=1),
        ),
    ]
